const IMAGE =
  "https://images.pexels.com/photos/20485643/pexels-photo-20485643/free-photo-of-rings-and-wedding-invitation.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load";

const sampleProducts = [
  {
    title: "Classic Cotton T-Shirt",
    description: "Soft everyday cotton tee available in multiple colors and sizes.",
    category: "tops",
    price: 499,
    discountPercentage: 10,
    rating: 4.5,
    brand: "YIOSI",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 120,
    variations: [
      {
        size: "M",
        colors: [
          { color: "black", colorCode: "#000000", stock: 40 },
          { color: "white", colorCode: "#FFFFFF", stock: 40 },
        ],
      },
      {
        size: "L",
        colors: [{ color: "navy", colorCode: "#001F3F", stock: 40 }],
      },
    ],
  },
  {
    title: "Wireless Bluetooth Headphones",
    description: "Noise-cancelling over-ear headphones with 30-hour battery life.",
    category: "smartphones",
    price: 2999,
    discountPercentage: 15,
    rating: 4.8,
    brand: "Samsung",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 50,
    variations: [
      {
        size: "One Size",
        colors: [{ color: "black", colorCode: "#000000", stock: 50 }],
      },
    ],
  },
  {
    title: "Polarized Sunglasses",
    description: "UV400 protection sunglasses with lightweight frame.",
    category: "sunglasses",
    price: 1299,
    discountPercentage: 20,
    rating: 4.2,
    brand: "Apple",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 35,
    variations: [
      {
        size: "Standard",
        colors: [
          { color: "gold", colorCode: "#FFD700", stock: 15 },
          { color: "silver", colorCode: "#C0C0C0", stock: 20 },
        ],
      },
    ],
  },
  {
    title: "Gold Pendant Necklace",
    description: "Elegant gold-plated pendant necklace for daily wear.",
    category: "womens jewellery",
    price: 1899,
    discountPercentage: 5,
    rating: 4.6,
    brand: "OPPO",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 25,
    variations: [
      {
        size: "16 inch",
        colors: [{ color: "gold", colorCode: "#FFD700", stock: 25 }],
      },
    ],
  },
  {
    title: "Men's Formal Shirt",
    description: "Slim-fit formal shirt suitable for office and events.",
    category: "mens shirts",
    price: 1599,
    discountPercentage: 12,
    rating: 4.3,
    brand: "HP Pavilion",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 60,
    variations: [
      {
        size: "M",
        colors: [
          { color: "blue", colorCode: "#0000FF", stock: 30 },
          { color: "white", colorCode: "#FFFFFF", stock: 30 },
        ],
      },
    ],
  },
  {
    title: "Running Sneakers",
    description: "Lightweight running shoes with cushioned sole.",
    category: "mens shoes",
    price: 2499,
    discountPercentage: 18,
    rating: 4.7,
    brand: "Samsung",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 45,
    variations: [
      {
        size: "42",
        colors: [{ color: "red", colorCode: "#FF0000", stock: 45 }],
      },
    ],
  },
  {
    title: "Leather Handbag",
    description: "Spacious leather handbag with multiple compartments.",
    category: "womens bags",
    price: 3499,
    discountPercentage: 25,
    rating: 4.4,
    brand: "Apple",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 20,
    variations: [
      {
        size: "Medium",
        colors: [{ color: "brown", colorCode: "#8B4513", stock: 20 }],
      },
    ],
  },
  {
    title: "Smart Watch Series X",
    description: "Fitness tracking smartwatch with heart-rate monitor.",
    category: "mens watches",
    price: 4999,
    discountPercentage: 10,
    rating: 4.9,
    brand: "Apple",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 30,
    variations: [
      {
        size: "44mm",
        colors: [
          { color: "black", colorCode: "#000000", stock: 15 },
          { color: "silver", colorCode: "#C0C0C0", stock: 15 },
        ],
      },
    ],
  },
  {
    title: "Organic Face Cream",
    description: "Hydrating face cream with natural ingredients.",
    category: "skincare",
    price: 799,
    discountPercentage: 8,
    rating: 4.1,
    brand: "OPPO",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 80,
    variations: [
      {
        size: "50ml",
        colors: [{ color: "white", colorCode: "#FFFFFF", stock: 80 }],
      },
    ],
  },
  {
    title: "Gaming Laptop Pro",
    description: "High-performance laptop with dedicated GPU for gaming.",
    category: "laptops",
    price: 89999,
    discountPercentage: 5,
    rating: 4.8,
    brand: "HP Pavilion",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 10,
    variations: [
      {
        size: "15.6 inch",
        colors: [{ color: "black", colorCode: "#000000", stock: 10 }],
      },
    ],
  },
  {
    title: "LED Desk Lamp",
    description: "Adjustable LED desk lamp with warm and cool modes.",
    category: "lighting",
    price: 1499,
    discountPercentage: 15,
    rating: 4.0,
    brand: "YIOSI",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: false,
    stock: 55,
    variations: [
      {
        size: "Standard",
        colors: [{ color: "white", colorCode: "#FFFFFF", stock: 55 }],
      },
    ],
  },
  {
    title: "Discontinued Vintage Camera",
    description: "Legacy product kept for admin soft-delete testing.",
    category: "automotive",
    price: 5999,
    discountPercentage: 0,
    rating: 3.5,
    brand: "OPPO",
    thumbnail: IMAGE,
    images: [IMAGE],
    deleted: true,
    stock: 0,
    variations: [
      {
        size: "Standard",
        colors: [{ color: "black", colorCode: "#000000", stock: 0 }],
      },
    ],
  },
];

module.exports = sampleProducts;
